# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  buildConfiguration: 'Release'

jobs:
- job: Linux_Build_and_Test
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      version: 3.1.x
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      projects: 'Xunit.DependencyInjection.Test/Xunit.DependencyInjection.Test.csproj'
      arguments: '-c $(buildConfiguration) -v n /p:TreatWarningsAsErrors=True'
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: 'Xunit.DependencyInjection.Test/Xunit.DependencyInjection.Test.csproj'
      arguments: '-c $(buildConfiguration)'
- job: MacOS_Build_and_Test
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      version: 3.1.x
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      projects: 'Xunit.DependencyInjection.Test/Xunit.DependencyInjection.Test.csproj'
      arguments: '-c $(buildConfiguration) -v n /p:TreatWarningsAsErrors=True'
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: 'Xunit.DependencyInjection.Test/Xunit.DependencyInjection.Test.csproj'
      arguments: '-c $(buildConfiguration)'
- job: Windows_Build_and_Test
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      version: 3.1.x
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      projects: 'Xunit.DependencyInjection.Test/Xunit.DependencyInjection.Test.csproj'
      arguments: '-c $(buildConfiguration) -v n /p:TreatWarningsAsErrors=True'
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: 'Xunit.DependencyInjection.Test/Xunit.DependencyInjection.Test.csproj'
      arguments: '-c $(buildConfiguration)'
