# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  buildConfiguration: 'Release'

jobs:
- job: Linux_Build_and_Test
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 2.1'
    inputs:
      version: 2.1.x
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 3.1'
    inputs:
      version: 3.1.x
  - task: UseDotNet@2
    displayName: 'Use .NET sdk 5.0'
    inputs:
      version: 5.0.x
  - script: dotnet build -c $(buildConfiguration) -v n /p:TreatWarningsAsErrors=True
    displayName: 'dotnet build'
  - script: dotnet test -c $(buildConfiguration) Xunit.DependencyInjection.Test/Xunit.DependencyInjection.Test.csproj
    displayName: 'dotnet test'
  - script: dotnet test -c $(buildConfiguration) Xunit.DependencyInjection.Test.AspNetCore/Xunit.DependencyInjection.Test.AspNetCore.csproj
    displayName: 'dotnet test aspnetcore'

- job: MacOS_Build_and_Test
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 2.1'
    inputs:
      version: 2.1.x
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 3.1'
    inputs:
      version: 3.1.x
  - task: UseDotNet@2
    displayName: 'Use .NET sdk 5.0'
    inputs:
      version: 5.0.x
  - script: dotnet build -c $(buildConfiguration) -v n /p:TreatWarningsAsErrors=True
    displayName: 'dotnet build'
  - script: dotnet test -c $(buildConfiguration) Xunit.DependencyInjection.Test/Xunit.DependencyInjection.Test.csproj
    displayName: 'dotnet test'
  - script: dotnet test -c $(buildConfiguration) Xunit.DependencyInjection.Test.AspNetCore/Xunit.DependencyInjection.Test.AspNetCore.csproj
    displayName: 'dotnet test aspnetcore'

- job: Windows_Build_and_Test
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 2.1'
    inputs:
      version: 2.1.x
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 3.1'
    inputs:
      version: 3.1.x
  - task: UseDotNet@2
    displayName: 'Use .NET sdk 5.0'
    inputs:
      version: 5.0.x
  - script: dotnet build -c $(buildConfiguration) -v n /p:TreatWarningsAsErrors=True
    displayName: 'dotnet build'
  - script: dotnet test -c $(buildConfiguration) Xunit.DependencyInjection.Test/Xunit.DependencyInjection.Test.csproj
    displayName: 'dotnet test'
  - script: dotnet test -c $(buildConfiguration) Xunit.DependencyInjection.Test.AspNetCore/Xunit.DependencyInjection.Test.AspNetCore.csproj
    displayName: 'dotnet test aspnetcore'
