# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  buildConfiguration: 'Release'

jobs:
- job: Linux_Build_and_Test
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.2.100'
  - task: DotNetCoreInstaller@0
    inputs:
      version: '3.0.100-preview7-012821'
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      projects: 'Xunit.DependencyInjection.Test/Xunit.DependencyInjection.Test.csproj'
      arguments: '-c $(buildConfiguration) -v n /p:TreatWarningsAsErrors=True'
      includePreviewVersions: true
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: 'Xunit.DependencyInjection.Test/Xunit.DependencyInjection.Test.csproj'
      arguments: '-c $(buildConfiguration)'
      includePreviewVersions: true
- job: MacOS_Build_and_Test
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.2.100'
  - task: DotNetCoreInstaller@0
    inputs:
      version: '3.0.100-preview7-012821'
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      projects: 'Xunit.DependencyInjection.Test/Xunit.DependencyInjection.Test.csproj'
      arguments: '-c $(buildConfiguration) -v n /p:TreatWarningsAsErrors=True'
      includePreviewVersions: true
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: 'Xunit.DependencyInjection.Test/Xunit.DependencyInjection.Test.csproj'
      arguments: '-c $(buildConfiguration)'
      includePreviewVersions: true
- job: Windows_Build_and_Test
  pool:
    vmImage: 'windows-2019'
  steps:
    - task: DotNetCoreInstaller@0
      inputs:
        version: '3.0.100-preview7-012821'
    - task: DotNetCoreCLI@2
      inputs:
        command: build
        projects: 'Xunit.DependencyInjection.Test/Xunit.DependencyInjection.Test.csproj'
        arguments: '-c $(buildConfiguration) -v n /p:TreatWarningsAsErrors=True'
        includePreviewVersions: true
    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: 'Xunit.DependencyInjection.Test/Xunit.DependencyInjection.Test.csproj'
        arguments: '-c $(buildConfiguration)'
        includePreviewVersions: true
